name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build for all architectures
      run: |
        set -e

        declare -a OS_LIST=("linux" "freebsd" "openbsd" "netbsd" "darwin" "windows")
        declare -a ARCH_LIST=("arm64" "amd64")
        declare -a EXTRA_ARCH_LINUX=("ppc64le" "riscv64" "s390x")

        echo "Building GoPlaylst binaries..."
        for OS in "${OS_LIST[@]}"; do
          for ARCH in "${ARCH_LIST[@]}"; do
            OUT_NAME="goplaylst_${OS}_${ARCH}"
            [ "$OS" == "windows" ] && OUT_NAME+=".exe"
            GOOS=$OS GOARCH=$ARCH CGO_ENABLED=0 go build -o "$OUT_NAME"
          done
        done

        # Handle additional Linux-specific architectures
        for ARCH in "${EXTRA_ARCH_LINUX[@]}"; do
          GOOS=linux GOARCH=$ARCH CGO_ENABLED=0 go build -o "goplaylst_linux_$ARCH"
        done

        echo "Building iTunesXML2CSV binaries..."
        cd iTunesXML2CSV
        for OS in "${OS_LIST[@]}"; do
          for ARCH in "${ARCH_LIST[@]}"; do
            OUT_NAME="itunesxml2csv_${OS}_${ARCH}"
            [ "$OS" == "windows" ] && OUT_NAME+=".exe"
            GOOS=$OS GOARCH=$ARCH CGO_ENABLED=0 go build -o ../"$OUT_NAME"
          done
        done
        cd -

        echo "Generate RELEASE.MD and LAST_CHANGES.md..."
        ./gen_release_log.sh
        ./extract_last_changes.sh

    - name: Upload executables
      uses: actions/upload-artifact@v3
      with:
        name: goplaylst-binaries
        path: |
          goplaylst_*
        retention-days: 7

    - name: Upload iTunesXML2CSV executables
      uses: actions/upload-artifact@v3
      with:
        name: itunesxml2csv-binaries
        path: |
          itunesxml2csv_*
        retention-days: 7

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        bodyFile: "LAST_CHANGES.md"

    - name: Get the Ref
      id: get-ref
      uses: ankitvgupta/ref-to-tag-action@master
      with:
        ref: ${{ github.ref }}
        head_ref: ${{ github.head_ref }}
